### ISSUE TITLE
This breaks ToS

### ISSUE THREAD

**Issue by Purpzie** [VoxelPrismatic/darkercord#1]
I've already notified you in a discord server, just posting this here for others to be warned until the readme is updated.

Discord doesn't _actively_ ban accounts that do things like this (at least not right now) unless they are abused. Things like this theme are still against ToS though technically - any modification to Discord, how it works/looks, etc, is against ToS.

**Comment by VoxelPrismatic** [comment]
I still disagree that it breaks ToS but okay, the README is updated

**Comment by Purpzie** [comment]
Thank you.
